# Site settings
title: Sanjay Patel - Blogs
description: A blog about lorem ipsum dolor sit amet
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sanjaypatel2525.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sanjay Patel
user_description: Developer at IBM
email: sanjaypatel2525@yahoo.com
twitter_username: 
github_username:  
gplus_username:  
disqus_username: 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about
  - Minify: Minify1
    url: /p

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']

plugins:
  - jekyll-admin